<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\Event\Event;

/**
 * Users Controller
 *
 * @property \App\Model\Table\UsersTable $Users
 *
 * @method \App\Model\Entity\User[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class UsersController extends AppController
{
    public function beforeFilter(Event $event)
    {
        $this->Auth->allow(['add']);
        if ($this->request->action == 'login' || $this->request->action == 'add') {
            if ($this->Auth->user()) {
                $this->Flash->error(__('You are already logged in'));
                return $this->redirect([
                    'controller' => 'Pages',
                    'action' => 'display'
                ]);
            }
        }
        return parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $user = $this->Users->newEntity();
        if ($this->request->is('post')) {
            $user = $this->Users->patchEntity($user, $this->request->getData());
            if ($this->Users->save($user)) {
                $this->Flash->success(__('The user has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The user could not be saved. Please, try again.'));
        }
        $this->set(compact('user'));
    }

    public function login(){
        if ($this->request->is('post')){
            $user=$this->Auth->identify();
            if($user){
                $this->Auth->setUser($user);

                return$this->redirect(['controller' => 'Pages', 'action' => 'display']);
            }
            $this->Flash->error('Verkeerde gegevens');
        }
    }
}
